services:
  backend:
    build:
      context: ./acteam-trains-backend
      dockerfile: Dockerfile
    volumes:
      - ./acteam-trains-backend:/var/www/html
    ports:
      - '8000:8000'
    networks:
      - app-network
    command: php artisan serve --host=0.0.0.0 --port=8000
  frontend:
    build:
      context: ./acteam-trains-frontend
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    networks:
      - app-network

networks:
	app-network:
		driver: bridge
